// <auto-generated />
using Honfoglalo.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Honfoglalo.DAL.Migrations
{
    [DbContext(typeof(HonfoglaloContext))]
    partial class HonfoglaloContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.DBSequenceHiLo", "'DBSequenceHiLo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.QuestionHiLo", "'QuestionHiLo', '', '100', '2', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:HiLoSequenceName", "DBSequenceHiLo")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

            modelBuilder.Entity("Honfoglalo.DAL.Model.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name")
                        .HasName("AK_Name");

                    b.HasIndex("Rank")
                        .HasName("Index_Rank");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "f11",
                            Rank = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "f12",
                            Rank = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "f13",
                            Rank = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "f14",
                            Rank = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "f15",
                            Rank = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "f16",
                            Rank = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "f17",
                            Rank = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "f18",
                            Rank = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "f19",
                            Rank = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "f110",
                            Rank = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "f111",
                            Rank = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "f112",
                            Rank = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "f113",
                            Rank = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "f114",
                            Rank = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "f115",
                            Rank = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "f116",
                            Rank = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "f117",
                            Rank = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "f118",
                            Rank = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "f119",
                            Rank = 5
                        },
                        new
                        {
                            Id = 20,
                            Name = "f120",
                            Rank = 5
                        });
                });

            modelBuilder.Entity("Honfoglalo.DAL.Model.FieldOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OwningTable");
                });

            modelBuilder.Entity("Honfoglalo.DAL.Model.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "QuestionHiLo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Question1")
                        .HasColumnName("Question1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty")
                        .HasName("Index_Difficulty");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "Correct Answer1",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 1"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "Correct Answer2",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 2"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "Correct Answer3",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 3"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "Correct Answer4",
                            Difficulty = 4,
                            IsDeleted = false,
                            Question1 = "Question 4"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "Correct Answer5",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 5"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "Correct Answer6",
                            Difficulty = 3,
                            IsDeleted = false,
                            Question1 = "Question 6"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "Correct Answer7",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 7"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswer = "Correct Answer8",
                            Difficulty = 3,
                            IsDeleted = false,
                            Question1 = "Question 8"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswer = "Correct Answer9",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 9"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswer = "Correct Answer10",
                            Difficulty = 5,
                            IsDeleted = false,
                            Question1 = "Question 10"
                        },
                        new
                        {
                            Id = 11,
                            CorrectAnswer = "Correct Answer11",
                            Difficulty = 5,
                            IsDeleted = false,
                            Question1 = "Question 11"
                        },
                        new
                        {
                            Id = 12,
                            CorrectAnswer = "Correct Answer12",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 12"
                        },
                        new
                        {
                            Id = 13,
                            CorrectAnswer = "Correct Answer13",
                            Difficulty = 4,
                            IsDeleted = false,
                            Question1 = "Question 13"
                        },
                        new
                        {
                            Id = 14,
                            CorrectAnswer = "Correct Answer14",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 14"
                        },
                        new
                        {
                            Id = 15,
                            CorrectAnswer = "Correct Answer15",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 15"
                        },
                        new
                        {
                            Id = 16,
                            CorrectAnswer = "Correct Answer16",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 16"
                        },
                        new
                        {
                            Id = 17,
                            CorrectAnswer = "Correct Answer17",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 17"
                        },
                        new
                        {
                            Id = 18,
                            CorrectAnswer = "Correct Answer18",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 18"
                        },
                        new
                        {
                            Id = 19,
                            CorrectAnswer = "Correct Answer19",
                            Difficulty = 4,
                            IsDeleted = false,
                            Question1 = "Question 19"
                        },
                        new
                        {
                            Id = 20,
                            CorrectAnswer = "Correct Answer20",
                            Difficulty = 5,
                            IsDeleted = false,
                            Question1 = "Question 20"
                        },
                        new
                        {
                            Id = 21,
                            CorrectAnswer = "Correct Answer21",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 21"
                        },
                        new
                        {
                            Id = 22,
                            CorrectAnswer = "Correct Answer22",
                            Difficulty = 3,
                            IsDeleted = false,
                            Question1 = "Question 22"
                        },
                        new
                        {
                            Id = 23,
                            CorrectAnswer = "Correct Answer23",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 23"
                        },
                        new
                        {
                            Id = 24,
                            CorrectAnswer = "Correct Answer24",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 24"
                        },
                        new
                        {
                            Id = 25,
                            CorrectAnswer = "Correct Answer25",
                            Difficulty = 3,
                            IsDeleted = false,
                            Question1 = "Question 25"
                        },
                        new
                        {
                            Id = 26,
                            CorrectAnswer = "Correct Answer26",
                            Difficulty = 3,
                            IsDeleted = false,
                            Question1 = "Question 26"
                        },
                        new
                        {
                            Id = 27,
                            CorrectAnswer = "Correct Answer27",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 27"
                        },
                        new
                        {
                            Id = 28,
                            CorrectAnswer = "Correct Answer28",
                            Difficulty = 5,
                            IsDeleted = false,
                            Question1 = "Question 28"
                        },
                        new
                        {
                            Id = 29,
                            CorrectAnswer = "Correct Answer29",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 29"
                        },
                        new
                        {
                            Id = 30,
                            CorrectAnswer = "Correct Answer30",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 30"
                        },
                        new
                        {
                            Id = 31,
                            CorrectAnswer = "Correct Answer31",
                            Difficulty = 4,
                            IsDeleted = false,
                            Question1 = "Question 31"
                        },
                        new
                        {
                            Id = 32,
                            CorrectAnswer = "Correct Answer32",
                            Difficulty = 3,
                            IsDeleted = false,
                            Question1 = "Question 32"
                        },
                        new
                        {
                            Id = 33,
                            CorrectAnswer = "Correct Answer33",
                            Difficulty = 3,
                            IsDeleted = false,
                            Question1 = "Question 33"
                        },
                        new
                        {
                            Id = 34,
                            CorrectAnswer = "Correct Answer34",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 34"
                        },
                        new
                        {
                            Id = 35,
                            CorrectAnswer = "Correct Answer35",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 35"
                        },
                        new
                        {
                            Id = 36,
                            CorrectAnswer = "Correct Answer36",
                            Difficulty = 5,
                            IsDeleted = false,
                            Question1 = "Question 36"
                        },
                        new
                        {
                            Id = 37,
                            CorrectAnswer = "Correct Answer37",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 37"
                        },
                        new
                        {
                            Id = 38,
                            CorrectAnswer = "Correct Answer38",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 38"
                        },
                        new
                        {
                            Id = 39,
                            CorrectAnswer = "Correct Answer39",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 39"
                        },
                        new
                        {
                            Id = 40,
                            CorrectAnswer = "Correct Answer40",
                            Difficulty = 5,
                            IsDeleted = false,
                            Question1 = "Question 40"
                        },
                        new
                        {
                            Id = 41,
                            CorrectAnswer = "Correct Answer41",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 41"
                        },
                        new
                        {
                            Id = 42,
                            CorrectAnswer = "Correct Answer42",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 42"
                        },
                        new
                        {
                            Id = 43,
                            CorrectAnswer = "Correct Answer43",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 43"
                        },
                        new
                        {
                            Id = 44,
                            CorrectAnswer = "Correct Answer44",
                            Difficulty = 4,
                            IsDeleted = false,
                            Question1 = "Question 44"
                        },
                        new
                        {
                            Id = 45,
                            CorrectAnswer = "Correct Answer45",
                            Difficulty = 5,
                            IsDeleted = false,
                            Question1 = "Question 45"
                        },
                        new
                        {
                            Id = 46,
                            CorrectAnswer = "Correct Answer46",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 46"
                        },
                        new
                        {
                            Id = 47,
                            CorrectAnswer = "Correct Answer47",
                            Difficulty = 3,
                            IsDeleted = false,
                            Question1 = "Question 47"
                        },
                        new
                        {
                            Id = 48,
                            CorrectAnswer = "Correct Answer48",
                            Difficulty = 2,
                            IsDeleted = false,
                            Question1 = "Question 48"
                        },
                        new
                        {
                            Id = 49,
                            CorrectAnswer = "Correct Answer49",
                            Difficulty = 4,
                            IsDeleted = false,
                            Question1 = "Question 49"
                        },
                        new
                        {
                            Id = 50,
                            CorrectAnswer = "Correct Answer50",
                            Difficulty = 1,
                            IsDeleted = false,
                            Question1 = "Question 50"
                        });
                });

            modelBuilder.Entity("Honfoglalo.DAL.Model.QuestionFieldLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DifficultyTable");
                });

            modelBuilder.Entity("Honfoglalo.DAL.Model.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumOfFields")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name")
                        .HasName("AK_User");

                    b.ToTable("UsersTable");
                });

            modelBuilder.Entity("Honfoglalo.DAL.Model.WinningHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoryTable");
                });

            modelBuilder.Entity("Honfoglalo.DAL.Model.WrongAnswers", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Answer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question1")
                        .HasColumnName("Question1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer1 = "Answer1_1",
                            Answer2 = "Answer2_1",
                            Answer3 = "Answer3_1",
                            Question1 = "Question 1"
                        },
                        new
                        {
                            Id = 2,
                            Answer1 = "Answer1_2",
                            Answer2 = "Answer2_2",
                            Answer3 = "Answer3_2",
                            Question1 = "Question 2"
                        },
                        new
                        {
                            Id = 3,
                            Answer1 = "Answer1_3",
                            Answer2 = "Answer2_3",
                            Answer3 = "Answer3_3",
                            Question1 = "Question 3"
                        },
                        new
                        {
                            Id = 4,
                            Answer1 = "Answer1_4",
                            Answer2 = "Answer2_4",
                            Answer3 = "Answer3_4",
                            Question1 = "Question 4"
                        },
                        new
                        {
                            Id = 5,
                            Answer1 = "Answer1_5",
                            Answer2 = "Answer2_5",
                            Answer3 = "Answer3_5",
                            Question1 = "Question 5"
                        },
                        new
                        {
                            Id = 6,
                            Answer1 = "Answer1_6",
                            Answer2 = "Answer2_6",
                            Answer3 = "Answer3_6",
                            Question1 = "Question 6"
                        },
                        new
                        {
                            Id = 7,
                            Answer1 = "Answer1_7",
                            Answer2 = "Answer2_7",
                            Answer3 = "Answer3_7",
                            Question1 = "Question 7"
                        },
                        new
                        {
                            Id = 8,
                            Answer1 = "Answer1_8",
                            Answer2 = "Answer2_8",
                            Answer3 = "Answer3_8",
                            Question1 = "Question 8"
                        },
                        new
                        {
                            Id = 9,
                            Answer1 = "Answer1_9",
                            Answer2 = "Answer2_9",
                            Answer3 = "Answer3_9",
                            Question1 = "Question 9"
                        },
                        new
                        {
                            Id = 10,
                            Answer1 = "Answer1_10",
                            Answer2 = "Answer2_10",
                            Answer3 = "Answer3_10",
                            Question1 = "Question 10"
                        },
                        new
                        {
                            Id = 11,
                            Answer1 = "Answer1_11",
                            Answer2 = "Answer2_11",
                            Answer3 = "Answer3_11",
                            Question1 = "Question 11"
                        },
                        new
                        {
                            Id = 12,
                            Answer1 = "Answer1_12",
                            Answer2 = "Answer2_12",
                            Answer3 = "Answer3_12",
                            Question1 = "Question 12"
                        },
                        new
                        {
                            Id = 13,
                            Answer1 = "Answer1_13",
                            Answer2 = "Answer2_13",
                            Answer3 = "Answer3_13",
                            Question1 = "Question 13"
                        },
                        new
                        {
                            Id = 14,
                            Answer1 = "Answer1_14",
                            Answer2 = "Answer2_14",
                            Answer3 = "Answer3_14",
                            Question1 = "Question 14"
                        },
                        new
                        {
                            Id = 15,
                            Answer1 = "Answer1_15",
                            Answer2 = "Answer2_15",
                            Answer3 = "Answer3_15",
                            Question1 = "Question 15"
                        },
                        new
                        {
                            Id = 16,
                            Answer1 = "Answer1_16",
                            Answer2 = "Answer2_16",
                            Answer3 = "Answer3_16",
                            Question1 = "Question 16"
                        },
                        new
                        {
                            Id = 17,
                            Answer1 = "Answer1_17",
                            Answer2 = "Answer2_17",
                            Answer3 = "Answer3_17",
                            Question1 = "Question 17"
                        },
                        new
                        {
                            Id = 18,
                            Answer1 = "Answer1_18",
                            Answer2 = "Answer2_18",
                            Answer3 = "Answer3_18",
                            Question1 = "Question 18"
                        },
                        new
                        {
                            Id = 19,
                            Answer1 = "Answer1_19",
                            Answer2 = "Answer2_19",
                            Answer3 = "Answer3_19",
                            Question1 = "Question 19"
                        },
                        new
                        {
                            Id = 20,
                            Answer1 = "Answer1_20",
                            Answer2 = "Answer2_20",
                            Answer3 = "Answer3_20",
                            Question1 = "Question 20"
                        },
                        new
                        {
                            Id = 21,
                            Answer1 = "Answer1_21",
                            Answer2 = "Answer2_21",
                            Answer3 = "Answer3_21",
                            Question1 = "Question 21"
                        },
                        new
                        {
                            Id = 22,
                            Answer1 = "Answer1_22",
                            Answer2 = "Answer2_22",
                            Answer3 = "Answer3_22",
                            Question1 = "Question 22"
                        },
                        new
                        {
                            Id = 23,
                            Answer1 = "Answer1_23",
                            Answer2 = "Answer2_23",
                            Answer3 = "Answer3_23",
                            Question1 = "Question 23"
                        },
                        new
                        {
                            Id = 24,
                            Answer1 = "Answer1_24",
                            Answer2 = "Answer2_24",
                            Answer3 = "Answer3_24",
                            Question1 = "Question 24"
                        },
                        new
                        {
                            Id = 25,
                            Answer1 = "Answer1_25",
                            Answer2 = "Answer2_25",
                            Answer3 = "Answer3_25",
                            Question1 = "Question 25"
                        },
                        new
                        {
                            Id = 26,
                            Answer1 = "Answer1_26",
                            Answer2 = "Answer2_26",
                            Answer3 = "Answer3_26",
                            Question1 = "Question 26"
                        },
                        new
                        {
                            Id = 27,
                            Answer1 = "Answer1_27",
                            Answer2 = "Answer2_27",
                            Answer3 = "Answer3_27",
                            Question1 = "Question 27"
                        },
                        new
                        {
                            Id = 28,
                            Answer1 = "Answer1_28",
                            Answer2 = "Answer2_28",
                            Answer3 = "Answer3_28",
                            Question1 = "Question 28"
                        },
                        new
                        {
                            Id = 29,
                            Answer1 = "Answer1_29",
                            Answer2 = "Answer2_29",
                            Answer3 = "Answer3_29",
                            Question1 = "Question 29"
                        },
                        new
                        {
                            Id = 30,
                            Answer1 = "Answer1_30",
                            Answer2 = "Answer2_30",
                            Answer3 = "Answer3_30",
                            Question1 = "Question 30"
                        },
                        new
                        {
                            Id = 31,
                            Answer1 = "Answer1_31",
                            Answer2 = "Answer2_31",
                            Answer3 = "Answer3_31",
                            Question1 = "Question 31"
                        },
                        new
                        {
                            Id = 32,
                            Answer1 = "Answer1_32",
                            Answer2 = "Answer2_32",
                            Answer3 = "Answer3_32",
                            Question1 = "Question 32"
                        },
                        new
                        {
                            Id = 33,
                            Answer1 = "Answer1_33",
                            Answer2 = "Answer2_33",
                            Answer3 = "Answer3_33",
                            Question1 = "Question 33"
                        },
                        new
                        {
                            Id = 34,
                            Answer1 = "Answer1_34",
                            Answer2 = "Answer2_34",
                            Answer3 = "Answer3_34",
                            Question1 = "Question 34"
                        },
                        new
                        {
                            Id = 35,
                            Answer1 = "Answer1_35",
                            Answer2 = "Answer2_35",
                            Answer3 = "Answer3_35",
                            Question1 = "Question 35"
                        },
                        new
                        {
                            Id = 36,
                            Answer1 = "Answer1_36",
                            Answer2 = "Answer2_36",
                            Answer3 = "Answer3_36",
                            Question1 = "Question 36"
                        },
                        new
                        {
                            Id = 37,
                            Answer1 = "Answer1_37",
                            Answer2 = "Answer2_37",
                            Answer3 = "Answer3_37",
                            Question1 = "Question 37"
                        },
                        new
                        {
                            Id = 38,
                            Answer1 = "Answer1_38",
                            Answer2 = "Answer2_38",
                            Answer3 = "Answer3_38",
                            Question1 = "Question 38"
                        },
                        new
                        {
                            Id = 39,
                            Answer1 = "Answer1_39",
                            Answer2 = "Answer2_39",
                            Answer3 = "Answer3_39",
                            Question1 = "Question 39"
                        },
                        new
                        {
                            Id = 40,
                            Answer1 = "Answer1_40",
                            Answer2 = "Answer2_40",
                            Answer3 = "Answer3_40",
                            Question1 = "Question 40"
                        },
                        new
                        {
                            Id = 41,
                            Answer1 = "Answer1_41",
                            Answer2 = "Answer2_41",
                            Answer3 = "Answer3_41",
                            Question1 = "Question 41"
                        },
                        new
                        {
                            Id = 42,
                            Answer1 = "Answer1_42",
                            Answer2 = "Answer2_42",
                            Answer3 = "Answer3_42",
                            Question1 = "Question 42"
                        },
                        new
                        {
                            Id = 43,
                            Answer1 = "Answer1_43",
                            Answer2 = "Answer2_43",
                            Answer3 = "Answer3_43",
                            Question1 = "Question 43"
                        },
                        new
                        {
                            Id = 44,
                            Answer1 = "Answer1_44",
                            Answer2 = "Answer2_44",
                            Answer3 = "Answer3_44",
                            Question1 = "Question 44"
                        },
                        new
                        {
                            Id = 45,
                            Answer1 = "Answer1_45",
                            Answer2 = "Answer2_45",
                            Answer3 = "Answer3_45",
                            Question1 = "Question 45"
                        },
                        new
                        {
                            Id = 46,
                            Answer1 = "Answer1_46",
                            Answer2 = "Answer2_46",
                            Answer3 = "Answer3_46",
                            Question1 = "Question 46"
                        },
                        new
                        {
                            Id = 47,
                            Answer1 = "Answer1_47",
                            Answer2 = "Answer2_47",
                            Answer3 = "Answer3_47",
                            Question1 = "Question 47"
                        },
                        new
                        {
                            Id = 48,
                            Answer1 = "Answer1_48",
                            Answer2 = "Answer2_48",
                            Answer3 = "Answer3_48",
                            Question1 = "Question 48"
                        },
                        new
                        {
                            Id = 49,
                            Answer1 = "Answer1_49",
                            Answer2 = "Answer2_49",
                            Answer3 = "Answer3_49",
                            Question1 = "Question 49"
                        },
                        new
                        {
                            Id = 50,
                            Answer1 = "Answer1_50",
                            Answer2 = "Answer2_50",
                            Answer3 = "Answer3_50",
                            Question1 = "Question 50"
                        });
                });

            modelBuilder.Entity("Honfoglalo.DAL.Model.Field", b =>
                {
                    b.OwnsOne("Honfoglalo.DAL.Model.Location", "FieldLocation", b1 =>
                        {
                            b1.Property<int>("FieldId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Region")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FieldId");

                            b1.ToTable("Fields");

                            b1.WithOwner()
                                .HasForeignKey("FieldId");

                            b1.HasData(
                                new
                                {
                                    FieldId = 1,
                                    Country = "Hungary",
                                    Region = "R10"
                                },
                                new
                                {
                                    FieldId = 2,
                                    Country = "Germany",
                                    Region = "R11"
                                },
                                new
                                {
                                    FieldId = 3,
                                    Country = "Germany",
                                    Region = "R12"
                                },
                                new
                                {
                                    FieldId = 4,
                                    Country = "Hungary",
                                    Region = "R13"
                                },
                                new
                                {
                                    FieldId = 5,
                                    Country = "Germany",
                                    Region = "R14"
                                },
                                new
                                {
                                    FieldId = 6,
                                    Country = "Germany",
                                    Region = "R15"
                                },
                                new
                                {
                                    FieldId = 7,
                                    Country = "Hungary",
                                    Region = "R16"
                                },
                                new
                                {
                                    FieldId = 8,
                                    Country = "Germany",
                                    Region = "R17"
                                },
                                new
                                {
                                    FieldId = 9,
                                    Country = "Germany",
                                    Region = "R18"
                                },
                                new
                                {
                                    FieldId = 10,
                                    Country = "Hungary",
                                    Region = "R19"
                                },
                                new
                                {
                                    FieldId = 11,
                                    Country = "Germany",
                                    Region = "R110"
                                },
                                new
                                {
                                    FieldId = 12,
                                    Country = "Germany",
                                    Region = "R111"
                                },
                                new
                                {
                                    FieldId = 13,
                                    Country = "Hungary",
                                    Region = "R112"
                                },
                                new
                                {
                                    FieldId = 14,
                                    Country = "Germany",
                                    Region = "R113"
                                },
                                new
                                {
                                    FieldId = 15,
                                    Country = "Germany",
                                    Region = "R114"
                                },
                                new
                                {
                                    FieldId = 16,
                                    Country = "Hungary",
                                    Region = "R115"
                                },
                                new
                                {
                                    FieldId = 17,
                                    Country = "Germany",
                                    Region = "R116"
                                },
                                new
                                {
                                    FieldId = 18,
                                    Country = "Germany",
                                    Region = "R117"
                                },
                                new
                                {
                                    FieldId = 19,
                                    Country = "Hungary",
                                    Region = "R118"
                                },
                                new
                                {
                                    FieldId = 20,
                                    Country = "Germany",
                                    Region = "R119"
                                });
                        });
                });

            modelBuilder.Entity("Honfoglalo.DAL.Model.WrongAnswers", b =>
                {
                    b.HasOne("Honfoglalo.DAL.Model.Question", null)
                        .WithOne("WrongAns")
                        .HasForeignKey("Honfoglalo.DAL.Model.WrongAnswers", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
